<a href="https://colab.research.google.com/github/alexrzntsv/TOBD-FU/blob/main/%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Создать в numpy матрицу 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [1]:
import numpy as np

In [17]:
data = np.linspace(1, 107, 107, dtype='int')
data[(data % 10 > 0) & (data % 10 < 8)].reshape(11, 7)

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  12,  13,  14,  15,  16,  17],
       [ 21,  22,  23,  24,  25,  26,  27],
       [ 31,  32,  33,  34,  35,  36,  37],
       [ 41,  42,  43,  44,  45,  46,  47],
       [ 51,  52,  53,  54,  55,  56,  57],
       [ 61,  62,  63,  64,  65,  66,  67],
       [ 71,  72,  73,  74,  75,  76,  77],
       [ 81,  82,  83,  84,  85,  86,  87],
       [ 91,  92,  93,  94,  95,  96,  97],
       [101, 102, 103, 104, 105, 106, 107]])

2. Средствами numpy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [20]:
np.arange(2, 21, 2) * np.arange(3, 22, 2) 

array([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

3. Создать две матрицы 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первой матрицы, которые больше соответсвующих (по расположению) значений второй матрицы. Подсчитать сумму этих значений.

In [30]:
np.random.seed(422)
arr_1 = np.random.randint(0, 10, (30, 3))
arr_2 = np.random.randint(0, 10, (30, 3))
mask = arr_1 > arr_2
arr_1[mask].sum()

349

4. Написать фукнцию, которая для целых значений n и m будет возвращать матрицу размера n на m, заполненую текстурой размера 2 на 2 состоящей из следующий значений:

```
0 1

2 3

```

Пример для n=5 и m = 4:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [79]:
def f(n, m):
  x = np.array([[0,1],[2,3]])
  return np.tile(x, (m, n))[:m, :n]
f(5, 4)

array([[0, 1, 0, 1, 0],
       [2, 3, 2, 3, 2],
       [0, 1, 0, 1, 0],
       [2, 3, 2, 3, 2]])

5. При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [93]:
np.random.seed(422)
arr = np.random.randint(0, 10, (20, 20))
print('Сама матрица: \n', arr)
row_indices = np.arange(0, 19, 1)
col_indices = row_indices + 1
print('результат:', arr[row_indices, col_indices])

Сама матрица: 
 [[7 8 8 4 7 5 9 4 1 7 9 6 4 2 7 7 2 9 7 8]
 [3 8 2 8 6 6 8 6 4 5 1 3 6 2 8 9 2 8 9 1]
 [7 4 0 1 8 1 4 9 4 0 8 3 2 5 8 3 6 8 8 6]
 [8 8 1 8 9 3 8 3 2 1 9 4 9 1 2 5 6 6 5 2]
 [2 9 9 0 9 5 3 6 6 1 8 4 1 7 0 4 8 1 7 2]
 [4 3 3 4 6 6 4 5 2 5 1 1 6 2 4 6 2 9 5 3]
 [8 6 5 9 1 8 5 3 5 4 7 8 3 6 0 3 1 0 3 8]
 [0 7 3 4 0 6 2 6 4 0 9 3 9 8 2 4 1 9 4 5]
 [4 4 8 6 7 1 5 8 3 4 3 6 1 0 6 8 6 9 2 6]
 [6 8 5 0 8 5 0 6 8 9 1 4 1 0 8 4 7 8 3 6]
 [9 2 3 0 8 9 7 9 0 6 7 4 4 5 2 4 2 9 4 9]
 [0 8 6 0 8 4 6 5 3 3 9 2 3 4 8 9 7 8 4 6]
 [3 5 0 8 0 7 2 9 1 6 4 1 8 3 1 6 1 5 0 7]
 [2 3 4 2 6 1 3 4 6 8 4 5 6 5 2 3 7 7 3 2]
 [0 1 8 9 8 5 5 1 3 4 8 0 3 7 9 4 8 5 5 4]
 [4 4 1 5 9 2 6 1 1 0 8 8 8 9 4 9 2 0 3 8]
 [6 6 9 1 8 3 0 5 8 8 6 9 5 2 3 3 5 5 4 4]
 [7 4 1 7 9 2 0 3 2 6 8 4 8 3 8 9 1 7 0 9]
 [6 9 2 3 1 4 4 6 0 1 3 5 5 2 1 5 0 1 1 7]
 [9 0 5 1 7 5 2 8 8 7 9 1 1 0 5 7 1 0 3 9]]
результат: [2 1 9 5 4 3 4 4 1 4 3 3 2 4 2 5 0 7]


6. Имеется массив из 10 названий городов. При помощи прихотливой индексации сгенерировать последовательность из 100 элементов представляющих случайный выбор из названий городов.

7. Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)) добиться расставки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]

```

In [106]:
arr = np.zeros((8, 8))
arr[1], arr[-2] = - np.ones((1, 8)), np.ones((1, 8)) 
arr

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-1., -1., -1., -1., -1., -1., -1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

8. Создать двухмерный массив 20 на 3, содержащийслучайные целые числа от 0 до 100. Интерпретируя массив как 20 векторов из 3х компонент, отсортировать массив по длине векторов.

In [115]:
np.random.seed(422)
arr = np.random.randint(0, 100, (20, 3))
mask = np.linalg.norm(arr, axis=1)
print(mask)
np.argsort(mask)[::-1]

[145.41320435 102.77159141 141.12760184  45.5521679   75.84853328
 118.38074168 132.27622613  59.71599451 123.28828006 119.7580895
  87.13782187  74.89993324  94.41927769 103.57605901  66.88049043
 109.22453937 107.78682665  88.00568163  44.28317965  79.80601481]


array([ 0,  2,  6,  8,  9,  5, 15, 16, 13,  1, 12, 17, 10, 19,  4, 11, 14,
        7,  3, 18])

9. Создать в numpy матрицу 11 на 7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]. При решении задачи применить технику распространения.

10. Создать массив из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в массиве. Опредлить индекс этого значения.