<a href="https://colab.research.google.com/github/alexrzntsv/TOBD-FU/blob/main/1/01_numpy_lr1_%D0%9F%D0%9821_2_%D0%A0%D1%8F%D0%B7%D0%B0%D0%BD%D1%86%D0%B5%D0%B2_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

In [2]:
import numpy as np

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [3]:
arr1 = np.linspace(0, 20, 28).reshape((4, 7))

result = (arr1 - np.min(arr1))/np.ptp(arr1)
print(result)

[[0.         0.03703704 0.07407407 0.11111111 0.14814815 0.18518519
  0.22222222]
 [0.25925926 0.2962963  0.33333333 0.37037037 0.40740741 0.44444444
  0.48148148]
 [0.51851852 0.55555556 0.59259259 0.62962963 0.66666667 0.7037037
  0.74074074]
 [0.77777778 0.81481481 0.85185185 0.88888889 0.92592593 0.96296296
  1.        ]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [4]:
arr = np.random.randint(0, 10, (8, 10))
print(arr[arr.sum(axis=1).argmin()], arr.sum(axis=1).argmin())

[0 3 6 7 3 2 1 6 0 8] 6


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [5]:
arr1 = np.array((1, 1, 1))
arr2 = np.array((4, 3, 2))

# вариант 1
#distance = np.linalg.norm(arr1-arr2)
#distance

# вариант 2
distance = np.sqrt(sum(pow(a-b, 2) for a, b in zip(arr1, arr2)))
distance

3.7416573867739413

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [6]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

X = np.matmul(np.matmul(np.linalg.inv(A), -C), np.linalg.inv(B))  
X

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1.1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [7]:
data = np.loadtxt('https://raw.githubusercontent.com/alexrzntsv/TOBD-FU/main/1/minutes_n_ingredients.csv', delimiter = ',', skiprows=1, dtype = 'int32')
data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [8]:
print('Mинимум:', data[:, 1:].min(axis=0))
print('Mаксимум:', data[:, 1:].max(axis=0))
print('Медиана:', np.median(data[:, 1:], axis=0))

Mинимум: [0 1]
Mаксимум: [2147483647         39]
Медиана: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [9]:
data[data[:, 1] < np.quantile(data[:, 1], 0.75)]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [371794,     35,      8],
       [ 43407,     35,      7],
       [370915,      5,      4]], dtype=int32)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [10]:
print(f'Продолжительность равна нулю для {data[data[:, 1] == 0].shape[0]} рецептов')

Продолжительность равна нулю для 479 рецептов


In [11]:
data[:, 1][data[:, 1] == 0] = 1

In [12]:
print(f'После замены осталось {data[data[:, 1] == 0].shape[0]} рецептов с продолжительностью 0')

После замены осталось 0 рецептов с продолжительностью 0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [13]:
print(f'Количество уникальных рецептов - {np.unique(data[:, 0], axis=0).shape[0]}')

Количество уникальных рецептов - 100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [14]:
import re
unique, counts = np.unique(data[:, 2], return_counts=True)
print(dict(zip(unique, counts)))

{1: 13, 2: 926, 3: 2895, 4: 5515, 5: 7913, 6: 9376, 7: 10628, 8: 10951, 9: 10585, 10: 9591, 11: 8297, 12: 6605, 13: 4997, 14: 3663, 15: 2595, 16: 1767, 17: 1246, 18: 790, 19: 573, 20: 376, 21: 217, 22: 161, 23: 105, 24: 69, 25: 50, 26: 28, 27: 16, 28: 16, 29: 12, 30: 12, 31: 3, 32: 1, 33: 2, 34: 1, 35: 3, 37: 1, 39: 1}


## Лабораторная работа №1.2

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [15]:
data_5 = data[data[:, 2] <= 5]
data_5[:5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       [484223,     18,      4],
       [ 63150,    250,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [16]:
data_mean = data[:, 2] / data[:, 1]
data_mean[:5]

array([0.26666667, 0.28      , 0.6       , 1.2       , 0.23333333])

In [17]:
print(f'Максимум: {data_mean.max()}')

Максимум: 24.0


In [18]:
# Решил посмотреть, что это за строка
data[data[:, 2] / data[:, 1] == 24.0]

array([[3137,    1,   24]], dtype=int32)

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [19]:
data[data[:, 1].argsort()][::-1][:100, 2].mean()

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [20]:
data[np.random.randint(0, data.shape[0], 10)]

array([[123466,     25,      9],
       [ 70759,     30,      9],
       [194727,     30,      4],
       [336354,    250,      5],
       [192165,     55,      8],
       [ 72495,     60,     10],
       [170495,     80,      8],
       [ 33720,     22,     10],
       [196506,     70,     12],
       [327358,     30,      5]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [21]:
print(f'{data[data[:,2] <data[:, 2].mean()].shape[0] / data.shape[0] * 100}%')

58.802%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [29]:
mask = ((data[:, 1] <= 20) & (data[:, 2] <= 5)).astype(int).reshape(-1, 1) 
new_data = np.hstack((data, mask))
new_data

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [30]:
print(f'{new_data[new_data[:, -1] == 1].shape[0] / new_data.shape[0] * 100}%')

9.552%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [57]:
#Отделяю сразу 3 группу
mask = (data[:, 1] >= 20).astype(int).reshape(-1, 1) 
new_data = np.hstack((data, mask))
data_3 = new_data[new_data[:, -1] == 1][:, :-1]
data_12 = new_data[new_data[:, -1] == 0]

# Разделяю 1 и 2 группы
data_12_mask = (data_12[:, 1] <= 10).astype(int).reshape(-1, 1)
data_12 = np.hstack((data_12, data_12_mask))
data_1 = data_12[data_12[:, -1] == 1][:, :-2]
data_2 = data_12[data_12[:, -1] == 0][:, :-2]

#Проверка правильности группировки:
#print(data_1.shape[0] , data_2.shape[0] , data_3.shape[0])

# Нахождение минимального из массивов
min_shape = min(data_1.shape[0], data_2.shape[0], data_3.shape[0])
res_data = np.array([data_1[:min_shape], data_2[:min_shape], data_3[:min_shape]])
res_data

array([[[ 94746,     10,      6],
        [ 67660,      5,      6],
        [366174,      7,      9],
        ...,
        [  7983,      1,      6],
        [184171,      5,      2],
        [ 89181,      5,      7]],

       [[ 33941,     18,      9],
        [446597,     15,      5],
        [ 81006,     12,      7],
        ...,
        [ 44120,     17,      5],
        [ 60756,     15,      5],
        [128811,     15,      4]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [186515,    220,     11],
        [372540,     50,      6],
        [172926,    120,     13]]])